# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MY BLOG
email: 1090313803@qq.com
description:  This is a personal blog to write down my experience during the learning life in IT area,and I'll share all I've studied here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: none
github_username:  LLLegend

# Build settings
markdown: kramdown
